#    partage_partage.example:
#        class: Partage\PartageBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
    app.form.registration:
        class: Partage\PartageBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }